apache/dubbo-go-hessian2

codec.go, const.go, decode.go, encode.go, encode_decode_test.go
1. fix bugs
2. add ref features
3. list decode refactor
=> fix bugs && add ref features && list decode refactor

request.go
=> ID->SerialID

codec.go
=> remove unuseful value type check

go.mod
=> remove go version required

codec.go, response.go, response_test.go
1.  refactoring response body object reflection
2. add unit test
=> fix dubbo response body object reflection

encode.go, pojo.go
参考append方法，将 encode 目标数组作为方法第一个参数，保持风格一致。
=> change encode target buf as the first parameter

.travis.yml, decode_test.go, test_dubbo/.gitignore, test_dubbo/README.md, test_dubbo/pom.xml, test_dubbo/src/main/java/test/Dubbo.java, test_dubbo/src/main/java/test/SimpleChannel.java, test_dubbo/src/main/java/test/TestDubbo.java, test_hessian/.gitignore, test_hessian/README.md, test_hessian/pom.xml, test_hessian/src/main/java/test/Hessian.java
- 添加了hessian序列化的java本地测试服务代码
- 添加了dubbo协议的java本地测试服务代码
=> 添加本地的java测试代码

binary.go, binary_test.go, boolean_test.go, codec_test.go, date.go, decode_test.go, encode_test.go, int_test.go, list_test.go, long_test.go, map_test.go, null_test.go
Improvement:
1 add "()" for import block even if just using one package
Bug fix:
1 gen hesissan jar by go command
=> Fix: gen hessian jar

.golangci.yml, Makefile, binary.go, boolean.go, codec.go, const.go, decode.go, double.go, encode.go, hessian.go, hessian_test.go, map.go, null_test.go, object.go, pojo.go, request.go, request_test.go, response.go, string.go
引入 gometalinter 和 golangci-lint
修正了一部分和社区规范不相符的问题(还有一些不太好改的，暂时没改)
常量似乎是改不了？
=> optimize code to match various lint tools

const.go, hessian.go, map.go, object.go, pojo.go, ref.go, request.go, string.go
PackageRequest_TwoWay is necessary in hessian.go#Write()
=> Fix:lack PackageRequest_TwoWay in Write

object.go
=> fix error msg in object.go

binary_test.go, decode_test.go, null_test.go, string_test.go
=> 添加decode string的测试

boolean_test.go, double_test.go, int_test.go, list_test.go, long_test.go, map_test.go, object_test.go
提高代码的复用率，减少冗余的decode framework代码
```release-note
None
```
=> reuse decode framework

hessian_test.go
add unit test for the map type of response
Fixes #37 
Currently, the supported decoding type of map is `map[interface{}]interface{}` , even when the type of map value is a array.  The following is the unit test:
```go
caseObj := Case{A: "a", B: 1}
mapObj := map[string][]*Case{"key": {&caseObj}}
mapRes := map[interface{}]interface{}{}
doTestResponse(t, PackageResponse, Response_OK, mapObj, &mapRes, func() {
c, ok := mapRes["key"]
if !ok {
assert.FailNow(t, "no key in decoded response map")
}
mapValueArr, ok := c.([]interface{})
if !ok {
assert.FailNow(t, "invalid decoded response map value", "expect []interface{}, but get %v", reflect.TypeOf(c))
}
assert.Equal(t, 1, len(mapValueArr)) …
```
=> fix issue #37

request.go, response.go
- fix bug about attachments
- update some todo
=> Fix: response nil attachments

README.md
fix syntax in readme
NONE
NONE
NONE
=> fix syntax in readme

hessian.go, response.go
fix: logic of exception decode and encode,  in order to be compatible with java
=> Fix:exception encode and decode

hessian.go, hessian_test.go, response.go
- java exception should not be returned as error
- java exception should be handled in the ReadBody
- java exception may also exist when heartbeat
=> Fix:java exception

hessian.go, response.go
=> Fix:exception enc/dec

double.go, long.go
=> Fix invalid data

boolean_test.go, double_test.go, int_test.go, long_test.go
- add double, int, long encode unit test
- merge after https://github.com/dubbogo/hessian2/pull/61, otherwise double unit test will fail
```release-note
none
```
=> add double, int, long encode unit test

java_exception/IOException.go, java_exception/array_store_exception.go, java_exception/classc_cast_exception.go, java_exception/enum_constant_not_present_exception.go, java_exception/illegal_monitor_state_exception.go, java_exception/illegal_state_exception.go, java_exception/runtime_exception.go
Fixes #
```release-note
Modify the author name of the source file
Jimmy zha --> ckex868@vip.qq.com
```
=> Modify the author name of the source file

binary.go, binary_test.go, date_test.go, encode_test.go, map.go, map_test.go, null_test.go, object_test.go, string_test.go
Add encode unit test for binary, date, null, object, string, map.
```release-note
none
```
=> Add: encode unit test

decode.go, java_exception.go, java_exception/completion_exception.go, java_exception/concurrent_modification_exception.go, java_exception/duplicate_format_flags_exception.go, java_exception/empty_stack_exception.go, java_exception/illegal_format_conversion_exception.go, java_exception/illegal_format_width_exception.go, java_exception/illformed_locale_exception.go, java_exception/missing_resource_exception.go, java_exception/no_such_element_exception.go, java_exception/rejected_execution_exception.go, java_exception_test.go, test_hessian/src/main/java/test/TestThrowable.java
Fixes #
```release-note
including:
IllegalFormatWidthException
IllegalFormatConversionException
DuplicateFormatFlagsException
MissingResourceException
ConcurrentModificationException
RejectedExecutionException
CompletionException
EmptyStackException
IllformedLocaleException
NoSuchElementException
```
=>  add exception

hessian.go
=> Mod:delete fmt.Println

object.go, pojo.go
just some error content. 
no
```release-note
NONE
```
=> improve error tips

list.go
=> Fix:fix bug

java_exception.go, java_exception/annotation_type_mismatch_exception.go, java_exception/exception.go, java_exception/incomplete_annotation_exception.go, java_exception_test.go, test_hessian/src/main/java/test/TestThrowable.java
=> add IncompleteAnnotationException And AnnotationTypeMismatchException

.travis.yml
Fix travis jdk version
None
None
None
=> fix travis jdk version

.travis.yml, binary.go, string.go
use gost bytes pool to reuse byte slices.
=> Imp: use gost bytes pool

README.md, go.mod, go.sum, java_exception.go, java_exception/exception.go, response.go
Fix package name after transfer
None
None
None
=> fix package name

encode.go, object.go, object_test.go
add bool nil 
golang bool nil fix
Fixes #113 
NONE
```release-note
```
=> [ISSUE #113 ]Feat boolnil

README.md
add features in readme: skipping unregistered pojo & emoji
=> Update: add "skipping unregistered pojo & emoji" in readme

int.go, long.go, request.go, response.go, string.go
remove  some worrying comments
=> remove comments

request.go
=> Fix: check service.Group and service.Interface

binary.go, go.mod, go.sum, string.go
=> update gost v1.5.1 bytes pool

CHANGE.md, NOTICE
update release note and notice for v1.4.0
=> release note and notice for v1.4.0

java_exception_test.go, response.go
=> fix the problems of v1.4

.travis.yml, before_validate_license.sh
=> Ftr:Add license checker

request.go, request_test.go
Fixes get attachment lost nil key, if the value is empty, get attachment will lost it
```release-note
```
=> fix get attachment lost nil key

string_test.go
=> remove unused comments.

string_test.go, test_hessian/src/main/java/test/TestCustomDecode.java, test_hessian/src/main/java/test/TestCustomReply.java, test_hessian/src/main/java/test/TestString.java
=> More unit tests

CHANGE.md, README.md
=> add release note for v1.6.0

request.go, request_test.go
=> merge bug fixes to 1.6

.travis.yml, output/output.go, output/testfuncs/string.go, test_hessian/pom.xml, test_hessian/src/test/java/unit/GoStringTest.java, test_hessian/src/test/java/unit/GoTestUtil.java
support test golang encoding data in java
=> support test golang encoding data in java

java8_time.go, java8_time/offset_date_time.go, java8_time/offset_time.go, java8_time/zone_off_set.go, java8_time/zoned_date_time.go, java8_time_test.go, test_hessian/src/main/java/test/TestJava8Time.java
java class java.time.ZoneOffset & java.time.OffsetDateTime & java.time.OffsetTime & java.time.ZonedDateTime refer to 
java8_time.ZoneOffSet & java8_time.OffsetDateTime & java8_time.OffsetTime & java8_time.ZonedDateTime
Fixes #
```release-note
```
=> ZoneOffSet & OffsetDateTime & OffsetTime & ZonedDateTime 

contributing.md, hessian.go, hessian_test.go, request.go, request_test.go, response.go, response_test.go
revert pr https://github.com/apache/dubbo-go-hessian2/pull/218
=> Fix: revert zhantu interface{} attachment

CHANGE.md
=> add release note for v1.8.0

request.go
the code same as https://github.com/apache/dubbo-go/pull/903
Fixes #
```release-note
```
=> [Fix] args struct javaclassname

date.go, go.mod, hessian.go, hessian_test.go, list.go, long.go, map.go, object.go, pojo.go, string.go
=> fix lint error

output/output.go, output/testfuncs/list.go, output/testfuncs/user.go, test_hessian/src/main/java/test/model/User.java, test_hessian/src/test/java/unit/GoUserListTest.java
add demo for reading go encode data to java list and array
=> add demo for reading go encode data to java list and array

codec.go, object.go, object_test.go, test_hessian/pom.xml, test_hessian/src/main/java/test/TestCustomReply.java
- fix not unpack ref holder for list
ref later.
=> fix not unpack ref holder for list

string_test.go, test_hessian/src/main/java/test/TestCustomReply.java
=> add unit test for #272

map.go
write BC_MAP_UNTYPED+BC_END for empty map instead null
=> write map tag for empty map instead of null

java_sql_time.go, object.go, pojo.go
update load pojo repository
Fixes #
fix:https://github.com/apache/dubbo-go-hessian2/issues/286
samples update hessian 1.9.4
=> update load pojo repository

Makefile, hessian_test/dup_struct_name_test.go, java_unknown_exception_test.go, list.go, pojo.go, pojo_test.go
- fix go type name for list
```release-note
- fix go type name for list
```
=> fix go type name for list

decode_test.go, map.go
#299
Fixes #
```release-note
```
=> reproduce decode interface map bug #299

list.go, object_test.go, test_hessian/src/main/java/test/TestCustomReply.java
revert unexpected merge : https://github.com/apache/dubbo-go-hessian2/compare/542bcf0e936b3cec6b8c76ddfb1d7304497d2380...868e06eb125c24ddf83d5f7934abf306105144e8
=> revert unexpected merge

string.go
**What this PR does**: fix memory leak issue
**Which issue(s) this PR fixes**: https://github.com/apache/dubbo-go-hessian2/issues/373
Fixes #
**Special notes for your reviewer**: directly returning a piece of a slice may cause a memory leak
```release-note
```
=> fix memory leak issue
