apache/dubbo-go-hessian2

request.go
request_test.go

fix bug that not initial the encoder in func ParkRequest

Fix encoder init

---

object.go
object_test.go
pojo.go

add feature for issues https://github.com/dubbogo/hessian2/issues/19

add: hessian TagIdentifier supportting #issues-19

---

decode.go
hessian_test.go
list.go
map.go
object.go
response.go

fix issue #35 to support hessian array response.
Notice:
1. now, list&map feature are not completed, the enhancement of which is added into [todo list](https://github.com/dubbogo/hessian2/wiki)
2. hessian codec cares about encode/decode, while dubbo request/response should not.

fix issue https://github.com/dubbogo/hessian2/issues/35

---

java_exception.go
java_exception/EOF_exception.go
java_exception/file_not_found_exception.go
java_exception/invalid_class_exception.go
java_exception/invalid_object_exception.go
java_exception/not_active_exception.go
java_exception/not_serializable_exception.go
java_exception/null_pointer_exception.go
java_exception/object_stream_exception.go
java_exception/optional_data_exception.go
java_exception/stream_corrupted_exception.go
java_exception/sync_failed_exception.go
java_exception/unchecked_IO_exception.go
java_exception/utf_data_format_exception.go
java_exception/write_aborted_exception.go
java_exception_test.go
test_hessian/src/main/java/test/TestThrowable.java

Add 7th java exception list of #59 
Fixes #
```release-note
NullPointerException
UncheckedIOException
FileNotFoundException
EOFException
SyncFailedException
ObjectStreamException
WriteAbortedException
InvalidObjectException
StreamCorruptedException
InvalidClassException
OptionalDataException
NotActiveException
NotSerializableException
UTFDataFormatException
```

Add: add some java exception

---

go.sum
hessian.go
request.go
response.go

- go mod tidy
- use `Request` and `Response`
Fixes #49
- user will make a Request or Response instead of body content.

Add:support attachments

---

codec.go
date.go
date_test.go
encode.go
object.go
test_hessian/src/main/java/test/TestCustomDecode.java
test_hessian/src/main/java/test/TestCustomReply.java
test_hessian/src/main/java/test/model/DateDemo.java

#90 
Fixes #
```release-note
```

Fix: date nil bug

---

request.go
response.go

Because the `map  `can only be resolved to `map[interface{}]interface{}` in the hessian2, I must be convert to `map[string]string`.
Fixes #
```release-note
```

Imp:  attachments

---

date_test.go
decode.go
decode_test.go
hessian.go
object.go
object_test.go
ref.go
request.go
response.go

support to read only attachments by "ReadAttachments"

---

const.go
request.go
response.go

Keep consistent with Java for response attachments.

Fix: dubbo version

---

Makefile
object.go
serialize.go
serialize_test.go
test_hessian/src/main/java/test/TestCustomReply.java

it can only decode Serializer object once. this PR fix it to allow duplicately decode Serializer objects. 
currently, it only decode  Serializer object when meeting class definition, but the Serializer object may occurs many times. 
```release-note
fix: can't duplicately decode Serializer object
```

fix: can't duplicately decode Serializer object

---

encode.go
go.mod
int.go
int_test.go

fix bug for encTypeInt32

---

object.go
object_test.go
test_hessian/src/main/java/test/TestCustomReply.java

- support extends to anonymouse field in go
Fixes #149 
how it works ?
findname will find field in all fields first, then find field in anonymous field, so that it can compatibility preview version 
```release-note
```

fix issue 149 - embed struct

---

README.md
object.go
object_test.go
pojo.go
test_hessian/src/main/java/test/TestCustomDecode.java
test_hessian/src/main/java/test/TestCustomReply.java

- flat anonymons fields
- ignore field with tag `hessian:"-"`
#153 
when find a anonymous field in scanning struct's fields, encoding/json will flat field immediately. but I put the field to queue and flat latter
```release-note
result of encode(object) has changed,
but the method decode is compatibility with previous version
```

Flat anonymous  struct field

---

README.md

Notice for inheritance
fix https://github.com/apache/dubbo-go-hessian2/issues/157

Notice for inheritance

---

README.md
java_collection.go
java_collection_test.go
list.go
test_hessian/src/main/java/test/TestCustomDecode.java
test_hessian/src/main/java/test/TestCustomReply.java

Add support for java collections such as HashSet
Collections are encoded through Serializer and decoded as list with regard of its type (collection types are encoded as the type of FixedTypedList in java impl of hessian). 
The collection struct implements are open for users, see what java_collection_test.go does.
Issue #122 
To reach the feature, code of method "readTypedList" in list.go also changes a little.
Related test codes of java side have also been added, see the last methods in TestCustomDecode.java & TestCustomReply.java
**Users need to implements collection structs and set them into go-hessian2, examples can be found in java_collection_test.go**

Ftr: add collection support according to java implementation

---

go.mod
object.go
object_test.go
pojo.go

Fixes #169 
```release-note
NONE
```

Imp: cache in reflection

---

decode.go
decode_test.go
string.go
string_test.go

Fixes #https://github.com/apache/dubbo-go-hessian2/issues/186
```release-note
NONE
```
优化思路：
1.  直接使用utf-8 byte解码，性能最高；之前先解码成 rune, 对rune解码成string，及其耗费性能
2.  增加批量string chunk copy, 降低read调用
3.  使用unsafe转换string

Perf decode string

---

.gitignore
string.go

- clean code
- NONE
```release-note
NONE
```

Code format

---

go.mod
request.go
request_test.go

fix the bug when eunm encode in request。
https://github.com/apache/dubbo-go-hessian2/issues/187

Fix: eunm encode in request get error

---

java8_time.go
java8_time/duration.go
java8_time/instant.go
java8_time/local_date.go
java8_time/local_date_time.go
java8_time/local_time.go
java8_time/month_day.go
java8_time/period.go
java8_time/year.go
java8_time/year_month.go
java8_time_test.go
test_hessian/src/main/java/test/Hessian.java
test_hessian/src/main/java/test/TestJava8Time.java

**What this PR does**: Add java8.time support
Fixes #193 
Only part of java8.time classes are supported now. Please review our framework of impelement. And we will coding for the reset classes asap if this PR is merged.

Feature java8 time

---

binary.go
decode_test.go
list.go

Fix issue 
Fixes #214 
```release-note
- Fix []byte field decoding issue
```

fix issue 214

---

decode_test.go
java_sql_time.go
java_sql_time/date.go
java_sql_time/java_sql_time.go
java_sql_time/time.go
java_sql_time_test.go
test_hessian/src/main/java/test/Hessian.java
test_hessian/src/main/java/test/TestJavaSqlTime.java

java class java.sql.Time & java.sql.Date refer to hessian.Time & hessian.Date
Fixes #
can use hessian.Time & hessian.Date in go for communicating with java.sql.Time & java.sql.Date in java
```release-note
```

java.sql.Time & java.sql.Date

---

encode.go
hessian_test.go
int.go
map.go
null.go
object.go
pojo.go
response.go

Export some function

---

output/output.go
output/testfuncs/java8_time.go
output/testfuncs/java_exception.go
test_hessian/src/test/java/unit/GoJava8TimeTest.java
test_hessian/src/test/java/unit/GoJavaExceptionTest.java

add support java8 time object. #212, #221
Fixes #
```release-note
```

add catch user defined exceptions. #208

---

decode_test.go
object.go
object_test.go
test_hessian/src/main/java/test/TestCustomReply.java
test_hessian/src/main/java/test/generic/BusinessData.java
test_hessian/src/main/java/test/generic/Response.java

fix issue #238 that cant decode java generic type
Fixes #238
```release-note
- fix issue that cant decode java generic type
```

fix issue that cant decode java generic type

---

decode.go
encode.go
java_collection.go
java_sql_time.go
java_unknown_exception.go
java_unknown_exception_test.go
list.go
object.go
object_test.go
pojo.go
serialize.go

using reference type to improve performance
NONE
```release-note
- using reference type to improve performance
```

rft: change value reference to ptr to improve performance

---

date.go
decode.go

Fix not enough buf error when decode date
Fixes #248
```release-note
Fix not enough buf error when decode date
```

fix not enough buf error when decode date

---

.travis.yml
string.go
string_test.go
test_hessian/src/main/java/test/TestCustomDecode.java
test_hessian/src/main/java/test/TestCustomReply.java
test_hessian/src/main/java/test/TestString.java

fix emoji decoding error and refactor string decoding algorithm, with 17% performance improvement
Fixes #252 #253
```release-note
- fix emoji decoding error and refactor string decoding algorithm, with 17% performance improvement
```

Fix emoji decoding error

---

string.go
string_test.go

Acquire sufficient bytes for string encoding buffers.
Fixes #253 
```release-note
- fix index out of range in some string encoding cases
```

Fix #253: Acquire sufficient bytes for string encoding buffers

---

decode.go
decode_test.go
map.go
map_test.go
object.go
serialize_test.go
test_hessian/src/main/java/test/TestCustomReply.java

Fix map decode error issue 
Fixes #259
the map type should be added into type map, not the class def map. see http://hessian.caucho.com/doc/hessian-serialization.html##type-map
```release-note
- Fix map decode error issue #259 
```

Fix map decode error issue #259

---

list.go
list_test.go
map.go
map_test.go
test_hessian/src/main/java/test/TestCustomReply.java
test_hessian/src/main/java/test/model/CustomMap.java

- fix duplicatedly adding list type in type map
- 
None
```release-note
- fix duplicatedly adding list type in type map
```

fix duplicatedly adding list type in type map

---

encode.go

reuse  allocated  buffer  when  buffer size < 128 byte.  it  not only  reuse  allocated  buffer , but also avoid  memory leak.

reuse allocated buffer

---

request.go

Fixed getArgType reflection value logic.
Source
Demo
Print
Analyse
`发现原版指向的类型是struct，如果使用t.Elem()会指向slice`
`测试了map，结果也是相似的`
Conclusion
`当getArgType的switch跑到default，且入参为指针时，很可能都会当成一般struct去处理`
Fixes #
```release-note
```

Fix: Fixed getArgType reflection value logic

---

array.go
array_test.go
object_test.go
output/output.go
output/testfuncs/wrapper_class_array.go
test_hessian/src/main/java/test/TestWrapperClassArray.java
test_hessian/src/test/java/unit/GoWrapperClassArrayTest.java

feat(*): support wrapper classes for Java basic types

---

codec.go
codec_test.go
encode.go
encode_test.go
serialize.go

When a user implements custom POJOs and uses non-pointer POJOs to encode, the encoding fails to transfer pojos forcibly. As a result, the program execution fails to meet expectations
When non-pointer structures are encoded, they are uniformly converted to Pointers for encoding
、
Fixes #
```release-note
```
Benchmark: 分别在struct以及pointer场景下 用串行以及8c并行 对当前pr与master进行对比。
// Benchmark_Struct_Encode  	 2231869	       506.8 ns/op	     560 B/op	       7 allocs/op
// Benchmark_Struct_Encode-master  	713761	      1549 ns/op	     560 B/op	       8 allocs/op
// Benchmark_Pointer_Encode   	 2565778	       476.1 ns/op	     560 B/op	       7 allocs/op
// …

convert pointer to encode

---

README.md
param.go

Supports specifying the types of Java method parameters.
golang decode fails when the Java interface receives a parameter type of parent class and is actually passed a subclass
Fixes #https://github.com/apache/dubbo-go-hessian2/issues/293
samples:
dubbo-go 修改点：
```release-note
```

support java function param type

---

codec.go
int.go
int_test.go
object_test.go
test_hessian/src/main/java/test/TestCustomReply.java
test_hessian/src/main/java/test/model/User.java

go decode support java integer null
Fixes https://github.com/apache/dubbo-go/issues/1637
```release-note
```

support java integer null

---

codec.go

When accessing a method whose return value is an enume value on the server, the client cannot parse the return value and reports an error. The tracing code found that the client could not convert the enum value type to Int64 type
You can reproduce the above problem through this code：https://github.com/luky116/dubbo-go-samples/tree/fix-rpcDubbo/rpc/dubbo

fix parse basic type bug

---

codec.go
decode_test.go
hessian_test.go
hessian_test/dup_struct_name_test.go
java_collection.go
list.go

fix list value not unpacked
Fixes #299
```release-note
- fix list value not unpacked. #299
```

fix list value not unpacked

---

double.go
double_test.go
test_hessian/src/main/java/test/TestCustomReply.java

fix #305, Java Double type to float64 get error  when null value set

---

map.go
map_test.go
test_hessian/src/main/java/test/TestCustomDecode.java

if map is pojo, write class name first
#319 
Fixes #
```release-note
```

if map is pojo, write class name first

---

hessian.go
request.go
response.go

mark dubbo2 rpc protocol implementation deprecated

mark dubbo2 rpc protocol implementation deprecated

---

ref.go
testcases/issue340/issue340_test.go

fix issue #340

---

array.go

mark array types deprecated,  to notice users the following types will not be supported in the next major version.
```go
hessian.IntegerArray
hessian.ByteArray
hessian.ShortArray
hessian.BooleanArray
hessian.LongArray
hessian.FloatArray
hessian.DoubleArray
hessian.CharacterArray
```

mark array types deprecated

---

.github/workflows/github-actions.yml
date.go
date_test.go

- upgrade go from v1.13 to v1.17
- using `time.UnixMills` api to release time scope limit
Fixes #348
NONE
```release-note
upgrade go from v1.13 to v1.17, and to use `time.UnixMills` api to release time scope limit
```

upgrade go to v1.17 to fix issue #348

---

.github/workflows/github-actions.yml
README.md
array.go
date.go
date_test.go

- upgrade go from v1.13 to v1.17
- using `time.UnixMills` api to release time scope limit
Fixes #348
NONE
```release-note
upgrade go from v1.13 to v1.17, and to use `time.UnixMills` api to release time scope limit
```

upgrade go to v1.17 to fix issue #348  for 2.0 branch

---

map.go
ref.go
testcases/issue356/issue356_test.go

fix issue #356 that ref to wrong type of map for nil value
Fixes #356
None
```release-note
fix issue #356 that ref to wrong type of map for nil value
```

fix issue 356 that ref to wrong type of map for nil value

---

map.go
map_test.go

Fix Decoder failed to decode int8/int16 type values of map field in struct
Currently, dubbo-go-hessian2 is unable to correctly decode values of type `int8` / `int16` that are contained within a `map` type field in a struct, resulting in a panic during the decoding process.
This PR is intended to fix this issue, which will enhance the compatibility between dubbo-go and dubbo-java.
I am a developer of the Kitex framework, and currently, [DubboCodec](https://github.com/kitex-contrib/codec-dubbo) is utilizing dubbo-go-hessian2 as its encoder/decoder. We also hope to resolve this issue through this PR, enabling us to support decoding of `int8` and `int16` types.
**Does this PR introduce a user-facing …

fix Decoder failed to decode int8/int16 type values of map field in struct
